logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 120

azstorage:
  type: block
  account-name: oslotestvideo
  account-key: zOevIegkZjld6ciTY+alA+YkzZ2gdAWVP7rkuhty5NAZ67AtiBB3fRTaa+eE3UbqhgwHZvWkOM0L+ASt4zCx6g==
  container: instavideo
  auth-type: accountKey
