logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 120

azstorage:
  type: block
  account-name: pyrenees
  account-key: 5Cb0dUA/ehCjlGmRWlIxuvG+eQ1308taRqt9EZp1tpk32UZxMUJa+1+PbwHw8YnwsnN9Syhi4EFf+AStZwrw6w==
  container: ingestvideo
  auth-type: accountKey
